#!/bin/sh
MATHJAX="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" 
pandoc -s --toc -N -t html5 --mathjax="$MATHJAX" -o doc/README.html README.md
pandoc -s --toc -N --mathjax="$MATHJAX" -o doc/README.xhtml README.md
pandoc -s --toc -N -o doc/README.pdf README.md
